### ISSUE TITLE
Workstation: Change look of scenery at runtime

### ISSUE THREAD

**Issue by hacklschorsch** [accu-rate/SumoVizUnity#1]
End-users often like to recognize what they know in the visualization output. To that end, we should like to implement some measures to change the looks of the vizualization. For example:
- Change textures and colors of objects,
- change the height of walls,
- Add/edit rooftops of houses
- ...

**Comment by benjaminaaron** [comment]
All of these changes are possible now because the scenario is imported at editing time and can be changed in any way. The trajectory data will be loaded at runtime.
