### ISSUE TITLE
Kamerafahrt aus Sicht simulierter Personen

### ISSUE THREAD

**Issue by hacklschorsch** [accu-rate/SumoVizUnity#2]
Für die normale und insbesondere für die Cardboard-Version: Kamerafahrt, die die Sicht eines Agenten zeigt.

**Comment by benjaminaaron** [comment]
`AgentView` is implemented :+1: 
The original implementation was done by @tsiliakis in [benjaminaaron/SumoVizUnity_ModSem](https://github.com/benjaminaaron/SumoVizUnity_ModSem/blob/master/Assets/Scripts/CameraModes/AgentView/AgentView.cs)
