### ISSUE TITLE
Write a new readme file

### ISSUE THREAD

**Issue by hacklschorsch** [accu-rate/SumoVizUnity#9]
Da steht immer noch die Einleitung von Daniel

**Comment by benjaminaaron** [comment]
Soll ich? :smiley:

**Comment by hacklschorsch** [comment]
sehr gern!

flo

On 14 March 2016 22:53:11 CET, Benjamin Aaron Degenhart notifications@github.com wrote:

> Soll ich? :smiley: 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/accu-rate/SumoVizUnity/issues/9#issuecomment-196537183

## 

Sent from my Mobile. Please excuse my brevity.

**Comment by benjaminaaron** [comment]
Ist in 04e8615 passiert :+1:
